version: "3"
services:
  app:
    image: ${DOCKER_USER}/spring-rest
    ports:
      - 8080:8080
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
#      start_period: 40s
